### ISSUE TITLE
JSON output is unreadable

### ISSUE THREAD

**Issue by SmokeyStack** [Mojang/minecraft-creator-tools#20]
Running `npx mctools-0.1.80.tgz validate -i build` will validate a folder called `build` and dump the output in an `out` folder. Inside this `out` folder, navigate to the JSON file. Going to the `index` key, that's where the unreadability occurs.
![image](https://github.com/Mojang/minecraft-creator-tools/assets/84206875/f1421066-f2b0-4966-a2c8-42aeada030e5)
 As you can see in the image above, the tool finds the common letter of the first index, and makes that an object, and the rest of the word as a key. This makes it hard to read.

**Comment by mammerla** [comment]
This ungainly JSON data structure is essentially an "index" of major elements from various files. Used mostly internally for things like "Ctrl-E" search.  I've removed the index from *.mcr.json files though in the newer build though.

Thanks for the feedback!
